# Generated by Django 2.2.4 on 2019-09-18 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True, verbose_name='Nombre')),
                ('rareza', models.IntegerField(blank=True, null=True, verbose_name='Rareza')),
                ('ataque', models.IntegerField(blank=True, null=True, verbose_name='Ataque')),
                ('defensa', models.IntegerField(blank=True, null=True, verbose_name='Defensa')),
            ],
        ),
        migrations.CreateModel(
            name='Mazo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jugador', models.CharField(max_length=20, null=True, verbose_name='Jugador')),
                ('carta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inicio.Carta')),
            ],
        ),
    ]
