# Generated by Django 2.2.6 on 2019-10-03 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carta',
            name='imagen',
            field=models.CharField(max_length=200, null=True, verbose_name='Nombre'),
        ),
    ]
