# Generated by Django 2.2.6 on 2019-10-03 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_carta_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carta',
            name='imagen',
            field=models.CharField(max_length=200, null=True, verbose_name='Imagen'),
        ),
    ]
