# Generated by Django 2.2.6 on 2019-10-03 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_auto_20191003_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='carta',
            name='lore',
            field=models.TextField(null=True, verbose_name='Lore'),
        ),
    ]
