# Generated by Django 2.2.6 on 2019-10-09 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_carta_lore'),
    ]

    operations = [
        migrations.AddField(
            model_name='mazo',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad'),
        ),
    ]
