# Generated by Django 2.2.4 on 2019-10-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0006_equipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='carta2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='carta3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='carta4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='carta5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carta',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
