# Generated by Django 2.2.4 on 2019-10-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0007_auto_20191009_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='carta1',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
