# Generated by Django 2.2.4 on 2019-10-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0008_auto_20191009_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='jugador',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Jugador'),
        ),
    ]
