# Generated by Django 2.2.6 on 2019-10-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0009_auto_20191009_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fotito',
            fields=[
                ('foto', models.TextField(null=True, verbose_name='Foto')),
                ('jugador', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Jugador')),
            ],
        ),
    ]
