// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.5.1
// source: tunel2/tunel2.proto

package tunel2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Packet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Types  string `protobuf:"bytes,2,opt,name=types,proto3" json:"types,omitempty"`
	Value  int32  `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	Origin string `protobuf:"bytes,4,opt,name=origin,proto3" json:"origin,omitempty"`
	Dest   string `protobuf:"bytes,5,opt,name=dest,proto3" json:"dest,omitempty"`
	Trys   string `protobuf:"bytes,6,opt,name=trys,proto3" json:"trys,omitempty"`
	Date   string `protobuf:"bytes,7,opt,name=date,proto3" json:"date,omitempty"`
}

func (x *Packet) Reset() {
	*x = Packet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tunel2_tunel2_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_tunel2_tunel2_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_tunel2_tunel2_proto_rawDescGZIP(), []int{0}
}

func (x *Packet) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Packet) GetTypes() string {
	if x != nil {
		return x.Types
	}
	return ""
}

func (x *Packet) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Packet) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *Packet) GetDest() string {
	if x != nil {
		return x.Dest
	}
	return ""
}

func (x *Packet) GetTrys() string {
	if x != nil {
		return x.Trys
	}
	return ""
}

func (x *Packet) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type Truck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Types int32 `protobuf:"varint,1,opt,name=types,proto3" json:"types,omitempty"`
}

func (x *Truck) Reset() {
	*x = Truck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tunel2_tunel2_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Truck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Truck) ProtoMessage() {}

func (x *Truck) ProtoReflect() protoreflect.Message {
	mi := &file_tunel2_tunel2_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Truck.ProtoReflect.Descriptor instead.
func (*Truck) Descriptor() ([]byte, []int) {
	return file_tunel2_tunel2_proto_rawDescGZIP(), []int{1}
}

func (x *Truck) GetTypes() int32 {
	if x != nil {
		return x.Types
	}
	return 0
}

type Tick struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok int32 `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *Tick) Reset() {
	*x = Tick{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tunel2_tunel2_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tick) ProtoMessage() {}

func (x *Tick) ProtoReflect() protoreflect.Message {
	mi := &file_tunel2_tunel2_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tick.ProtoReflect.Descriptor instead.
func (*Tick) Descriptor() ([]byte, []int) {
	return file_tunel2_tunel2_proto_rawDescGZIP(), []int{2}
}

func (x *Tick) GetOk() int32 {
	if x != nil {
		return x.Ok
	}
	return 0
}

var File_tunel2_tunel2_proto protoreflect.FileDescriptor

var file_tunel2_tunel2_proto_rawDesc = []byte{
	0x0a, 0x13, 0x74, 0x75, 0x6e, 0x65, 0x6c, 0x32, 0x2f, 0x74, 0x75, 0x6e, 0x65, 0x6c, 0x32, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x74, 0x72, 0x61, 0x63, 0x69, 0x6e, 0x67, 0x32, 0x22,
	0x98, 0x01, 0x0a, 0x06, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x65, 0x73, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x72, 0x79, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x72, 0x79, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x22, 0x1d, 0x0a, 0x05, 0x54, 0x72,
	0x75, 0x63, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x22, 0x16, 0x0a, 0x04, 0x54, 0x69, 0x63,
	0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x6f,
	0x6b, 0x32, 0x6b, 0x0a, 0x07, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x12, 0x32, 0x0a, 0x0b,
	0x47, 0x69, 0x6d, 0x6d, 0x65, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x0f, 0x2e, 0x74, 0x72,
	0x61, 0x63, 0x69, 0x6e, 0x67, 0x32, 0x2e, 0x54, 0x72, 0x75, 0x63, 0x6b, 0x1a, 0x10, 0x2e, 0x74,
	0x72, 0x61, 0x63, 0x69, 0x6e, 0x67, 0x32, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x22, 0x00,
	0x12, 0x2c, 0x0a, 0x06, 0x49, 0x6d, 0x42, 0x61, 0x63, 0x6b, 0x12, 0x10, 0x2e, 0x74, 0x72, 0x61,
	0x63, 0x69, 0x6e, 0x67, 0x32, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x1a, 0x0e, 0x2e, 0x74,
	0x72, 0x61, 0x63, 0x69, 0x6e, 0x67, 0x32, 0x2e, 0x54, 0x69, 0x63, 0x6b, 0x22, 0x00, 0x42, 0x0f,
	0x5a, 0x0d, 0x74, 0x61, 0x72, 0x65, 0x61, 0x31, 0x2f, 0x74, 0x75, 0x6e, 0x65, 0x6c, 0x32, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tunel2_tunel2_proto_rawDescOnce sync.Once
	file_tunel2_tunel2_proto_rawDescData = file_tunel2_tunel2_proto_rawDesc
)

func file_tunel2_tunel2_proto_rawDescGZIP() []byte {
	file_tunel2_tunel2_proto_rawDescOnce.Do(func() {
		file_tunel2_tunel2_proto_rawDescData = protoimpl.X.CompressGZIP(file_tunel2_tunel2_proto_rawDescData)
	})
	return file_tunel2_tunel2_proto_rawDescData
}

var file_tunel2_tunel2_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_tunel2_tunel2_proto_goTypes = []interface{}{
	(*Packet)(nil), // 0: tracing2.Packet
	(*Truck)(nil),  // 1: tracing2.Truck
	(*Tick)(nil),   // 2: tracing2.Tick
}
var file_tunel2_tunel2_proto_depIdxs = []int32{
	1, // 0: tracing2.Greeter.GimmePacket:input_type -> tracing2.Truck
	0, // 1: tracing2.Greeter.ImBack:input_type -> tracing2.Packet
	0, // 2: tracing2.Greeter.GimmePacket:output_type -> tracing2.Packet
	2, // 3: tracing2.Greeter.ImBack:output_type -> tracing2.Tick
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tunel2_tunel2_proto_init() }
func file_tunel2_tunel2_proto_init() {
	if File_tunel2_tunel2_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tunel2_tunel2_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Packet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tunel2_tunel2_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Truck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tunel2_tunel2_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tick); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tunel2_tunel2_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tunel2_tunel2_proto_goTypes,
		DependencyIndexes: file_tunel2_tunel2_proto_depIdxs,
		MessageInfos:      file_tunel2_tunel2_proto_msgTypes,
	}.Build()
	File_tunel2_tunel2_proto = out.File
	file_tunel2_tunel2_proto_rawDesc = nil
	file_tunel2_tunel2_proto_goTypes = nil
	file_tunel2_tunel2_proto_depIdxs = nil
}
