prob1-bf: Problema1/FuerzaBruta.cpp
	g++ Problema1/FuerzaBruta.cpp -o out -Wall

prob1-dc: Problema1/DividirYConquistar.cpp
	g++ Problema1/DividirYConquistar.cpp -o out -Wall

prob2: Problema2/problema2.cpp
	g++ Problema2/problema2.cpp -o out -Wall